#name: ci
#
#on:
#  push:
#    branches:
#      - "main"
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Login to GitHub Package Registry
#        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.crownlabs.polito.it -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin
