name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.crownlabs.polito.it -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_USERNAME }}/flask-api:latest